import { MigrationInterface, QueryRunner } from "typeorm";

export class InitErpSchema1786870377085 implements MigrationInterface {
    name = 'InitErpSchema1786870377085'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`CREATE TABLE \`tenant\` (\`id\` int NOT NULL AUTO_INCREMENT, \`code\` varchar(32) NOT NULL COMMENT '公司编码（登录用）', \`name\` varchar(64) NOT NULL COMMENT '公司名称', \`status\` tinyint NOT NULL COMMENT '0停用 1启用' DEFAULT '1', \`created_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`updated_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), UNIQUE INDEX \`IDX_b1bb8505abe259d04b317bd799\` (\`code\`), PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`sys_user\` (\`company_id\` int NOT NULL COMMENT '所属租户', \`id\` int NOT NULL AUTO_INCREMENT, \`username\` varchar(32) NOT NULL COMMENT '登录名', \`password\` varchar(100) NOT NULL COMMENT 'bcrypt 哈希', \`real_name\` varchar(32) NULL, \`phone\` varchar(20) NULL, \`email\` varchar(64) NULL, \`status\` tinyint NOT NULL COMMENT '0停用 1启用' DEFAULT '1', \`is_super_admin\` tinyint NOT NULL COMMENT '平台超管（跨租户运维）' DEFAULT '0', \`created_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`updated_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), UNIQUE INDEX \`IDX_73b9691048355487ae9dd14aa6\` (\`company_id\`, \`username\`), PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`sys_role\` (\`company_id\` int NOT NULL COMMENT '所属租户', \`id\` int NOT NULL AUTO_INCREMENT, \`name\` varchar(32) NOT NULL, \`code\` varchar(32) NOT NULL COMMENT '角色编码，如 SUPER_ADMIN', \`remark\` varchar(200) NULL, \`status\` tinyint NOT NULL COMMENT '0停用 1启用' DEFAULT '1', \`created_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`updated_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), UNIQUE INDEX \`IDX_03ed73db3445ce410474d1cc7f\` (\`company_id\`, \`code\`), PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`sys_role_permission\` (\`id\` int NOT NULL AUTO_INCREMENT, \`role_id\` int NOT NULL, \`permission_id\` int NOT NULL, UNIQUE INDEX \`IDX_980f2d8e546d791d992408b2c4\` (\`role_id\`, \`permission_id\`), PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`sys_user_role\` (\`id\` int NOT NULL AUTO_INCREMENT, \`user_id\` int NOT NULL, \`role_id\` int NOT NULL, UNIQUE INDEX \`IDX_2e8de9f75bef43b05dc1eb09ed\` (\`user_id\`, \`role_id\`), PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`sys_permission\` (\`id\` int NOT NULL AUTO_INCREMENT, \`parent_id\` int NOT NULL DEFAULT '0', \`name\` varchar(32) NOT NULL, \`code\` varchar(64) NOT NULL COMMENT '权限码，如 sale:order:outbound', \`type\` varchar(16) NOT NULL, \`path\` varchar(128) NULL COMMENT '前端路由路径', \`icon\` varchar(32) NULL COMMENT '图标名', \`sort\` int NOT NULL DEFAULT '0', \`status\` tinyint NOT NULL DEFAULT '1', UNIQUE INDEX \`IDX_ba9809c4237d793d905045f04e\` (\`code\`), PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`sys_operation_log\` (\`company_id\` int NOT NULL COMMENT '所属租户', \`id\` int NOT NULL AUTO_INCREMENT, \`user_id\` int NULL, \`username\` varchar(32) NULL, \`module\` varchar(32) NOT NULL COMMENT '模块', \`action\` varchar(64) NOT NULL COMMENT '动作', \`method\` varchar(8) NOT NULL, \`path\` varchar(128) NOT NULL, \`params\` text NULL COMMENT '请求参数（截断）', \`ip\` varchar(64) NULL, \`created_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`product_category\` (\`company_id\` int NOT NULL COMMENT '所属租户', \`id\` int NOT NULL AUTO_INCREMENT, \`parent_id\` int NOT NULL COMMENT '父分类，0 为顶级' DEFAULT '0', \`name\` varchar(32) NOT NULL, \`sort\` int NOT NULL DEFAULT '0', \`status\` tinyint NOT NULL DEFAULT '1', \`created_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`updated_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`product\` (\`company_id\` int NOT NULL COMMENT '所属租户', \`id\` int NOT NULL AUTO_INCREMENT, \`category_id\` int NOT NULL DEFAULT '0', \`code\` varchar(32) NOT NULL COMMENT '商品编码', \`name\` varchar(64) NOT NULL, \`spec\` varchar(64) NULL COMMENT '规格型号', \`unit\` varchar(16) NULL COMMENT '单位', \`purchase_price\` decimal(12,2) NOT NULL COMMENT '采购价' DEFAULT '0.00', \`sale_price\` decimal(12,2) NOT NULL COMMENT '销售价' DEFAULT '0.00', \`safety_stock\` decimal(12,2) NOT NULL COMMENT '安全库存，低于则预警' DEFAULT '0.00', \`image\` varchar(255) NULL COMMENT '图片 URL', \`remark\` varchar(255) NULL, \`status\` tinyint NOT NULL DEFAULT '1', \`created_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`updated_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), UNIQUE INDEX \`IDX_d4a93f0caa54cce1e3e76bd987\` (\`company_id\`, \`code\`), PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`supplier\` (\`company_id\` int NOT NULL COMMENT '所属租户', \`id\` int NOT NULL AUTO_INCREMENT, \`code\` varchar(32) NOT NULL, \`name\` varchar(64) NOT NULL, \`contact\` varchar(32) NULL, \`phone\` varchar(20) NULL, \`address\` varchar(200) NULL, \`remark\` varchar(255) NULL, \`status\` tinyint NOT NULL DEFAULT '1', \`created_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`updated_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), UNIQUE INDEX \`IDX_7098388282f53f8c138e5fb60d\` (\`company_id\`, \`code\`), PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`customer\` (\`company_id\` int NOT NULL COMMENT '所属租户', \`id\` int NOT NULL AUTO_INCREMENT, \`code\` varchar(32) NOT NULL, \`name\` varchar(64) NOT NULL, \`contact\` varchar(32) NULL, \`phone\` varchar(20) NULL, \`address\` varchar(200) NULL, \`level\` varchar(32) NULL COMMENT '客户等级', \`remark\` varchar(255) NULL, \`status\` tinyint NOT NULL DEFAULT '1', \`created_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`updated_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), UNIQUE INDEX \`IDX_da15043b367546a1b25470accd\` (\`company_id\`, \`code\`), PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`purchase_order\` (\`company_id\` int NOT NULL COMMENT '所属租户', \`id\` int NOT NULL AUTO_INCREMENT, \`order_no\` varchar(32) NOT NULL, \`supplier_id\` int NOT NULL, \`supplier_name\` varchar(64) NOT NULL COMMENT '冗余供应商名', \`order_date\` date NOT NULL, \`total_amount\` decimal(12,2) NOT NULL COMMENT '订单总额' DEFAULT '0.00', \`paid_amount\` decimal(12,2) NOT NULL COMMENT '已付金额' DEFAULT '0.00', \`status\` varchar(16) NOT NULL DEFAULT 'draft', \`remark\` varchar(255) NULL, \`created_by\` int NULL, \`created_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`updated_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), UNIQUE INDEX \`IDX_b26e19e4aaf364e7d057284c5d\` (\`company_id\`, \`order_no\`), PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`purchase_order_item\` (\`id\` int NOT NULL AUTO_INCREMENT, \`order_id\` int NOT NULL, \`product_id\` int NOT NULL, \`product_name\` varchar(64) NOT NULL COMMENT '冗余商品名', \`spec\` varchar(64) NULL, \`unit\` varchar(16) NULL, \`quantity\` decimal(12,2) NOT NULL DEFAULT '0.00', \`price\` decimal(12,2) NOT NULL DEFAULT '0.00', \`amount\` decimal(12,2) NOT NULL DEFAULT '0.00', PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`sale_order\` (\`company_id\` int NOT NULL COMMENT '所属租户', \`id\` int NOT NULL AUTO_INCREMENT, \`order_no\` varchar(32) NOT NULL, \`customer_id\` int NOT NULL, \`customer_name\` varchar(64) NOT NULL COMMENT '冗余客户名', \`order_date\` date NOT NULL, \`total_amount\` decimal(12,2) NOT NULL DEFAULT '0.00', \`paid_amount\` decimal(12,2) NOT NULL DEFAULT '0.00', \`status\` varchar(16) NOT NULL DEFAULT 'draft', \`remark\` varchar(255) NULL, \`created_by\` int NULL, \`created_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`updated_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), UNIQUE INDEX \`IDX_92db8b47c37bb286279f5c5f08\` (\`company_id\`, \`order_no\`), PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`sale_order_item\` (\`id\` int NOT NULL AUTO_INCREMENT, \`order_id\` int NOT NULL, \`product_id\` int NOT NULL, \`product_name\` varchar(64) NOT NULL, \`spec\` varchar(64) NULL, \`unit\` varchar(16) NULL, \`quantity\` decimal(12,2) NOT NULL DEFAULT '0.00', \`price\` decimal(12,2) NOT NULL DEFAULT '0.00', \`amount\` decimal(12,2) NOT NULL DEFAULT '0.00', PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`purchase_inbound\` (\`company_id\` int NOT NULL COMMENT '所属租户', \`id\` int NOT NULL AUTO_INCREMENT, \`inbound_no\` varchar(32) NOT NULL, \`order_id\` int NULL COMMENT '关联采购订单，直接入库为空', \`supplier_id\` int NOT NULL, \`supplier_name\` varchar(64) NOT NULL, \`inbound_date\` date NOT NULL, \`total_amount\` decimal(12,2) NOT NULL DEFAULT '0.00', \`remark\` varchar(255) NULL, \`created_by\` int NULL, \`created_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), UNIQUE INDEX \`IDX_4c8d9f2da9306e8768eaeb01df\` (\`company_id\`, \`inbound_no\`), PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`purchase_inbound_item\` (\`id\` int NOT NULL AUTO_INCREMENT, \`inbound_id\` int NOT NULL, \`product_id\` int NOT NULL, \`product_name\` varchar(64) NOT NULL, \`spec\` varchar(64) NULL, \`unit\` varchar(16) NULL, \`quantity\` decimal(12,2) NOT NULL DEFAULT '0.00', \`price\` decimal(12,2) NOT NULL DEFAULT '0.00', \`amount\` decimal(12,2) NOT NULL DEFAULT '0.00', PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`sale_outbound\` (\`company_id\` int NOT NULL COMMENT '所属租户', \`id\` int NOT NULL AUTO_INCREMENT, \`outbound_no\` varchar(32) NOT NULL, \`order_id\` int NULL, \`customer_id\` int NOT NULL, \`customer_name\` varchar(64) NOT NULL, \`outbound_date\` date NOT NULL, \`total_amount\` decimal(12,2) NOT NULL DEFAULT '0.00', \`remark\` varchar(255) NULL, \`created_by\` int NULL, \`created_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), UNIQUE INDEX \`IDX_38ce723a63c1fabf190af97fe9\` (\`company_id\`, \`outbound_no\`), PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`sale_outbound_item\` (\`id\` int NOT NULL AUTO_INCREMENT, \`outbound_id\` int NOT NULL, \`product_id\` int NOT NULL, \`product_name\` varchar(64) NOT NULL, \`spec\` varchar(64) NULL, \`unit\` varchar(16) NULL, \`quantity\` decimal(12,2) NOT NULL DEFAULT '0.00', \`price\` decimal(12,2) NOT NULL DEFAULT '0.00', \`amount\` decimal(12,2) NOT NULL DEFAULT '0.00', PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`inventory\` (\`company_id\` int NOT NULL COMMENT '所属租户', \`id\` int NOT NULL AUTO_INCREMENT, \`product_id\` int NOT NULL, \`quantity\` decimal(12,2) NOT NULL COMMENT '当前库存数量' DEFAULT '0.00', \`updated_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), UNIQUE INDEX \`IDX_2aa58340b21f8eb450603b09e4\` (\`company_id\`, \`product_id\`), PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`inventory_record\` (\`company_id\` int NOT NULL COMMENT '所属租户', \`id\` int NOT NULL AUTO_INCREMENT, \`product_id\` int NOT NULL, \`product_name\` varchar(64) NOT NULL COMMENT '冗余商品名（列表免 join）', \`type\` varchar(16) NOT NULL, \`quantity\` decimal(12,2) NOT NULL COMMENT '本次变动数量（出库为负）' DEFAULT '0.00', \`balance_after\` decimal(12,2) NOT NULL COMMENT '变动后结余' DEFAULT '0.00', \`ref_type\` varchar(32) NOT NULL COMMENT '来源类型，如 SALE_OUTBOUND', \`ref_no\` varchar(64) NOT NULL COMMENT '来源单号', \`remark\` varchar(255) NULL, \`operator\` varchar(32) NULL, \`created_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`stocktake\` (\`company_id\` int NOT NULL COMMENT '所属租户', \`id\` int NOT NULL AUTO_INCREMENT, \`stocktake_no\` varchar(32) NOT NULL, \`status\` varchar(16) NOT NULL DEFAULT 'draft', \`remark\` varchar(255) NULL, \`created_by\` int NULL, \`created_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), UNIQUE INDEX \`IDX_18f72a9ee0258a1a4435b8d955\` (\`company_id\`, \`stocktake_no\`), PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`stocktake_item\` (\`id\` int NOT NULL AUTO_INCREMENT, \`stocktake_id\` int NOT NULL, \`product_id\` int NOT NULL, \`product_name\` varchar(64) NOT NULL, \`book_qty\` decimal(12,2) NOT NULL COMMENT '账面数量' DEFAULT '0.00', \`actual_qty\` decimal(12,2) NOT NULL COMMENT '实盘数量' DEFAULT '0.00', \`diff_qty\` decimal(12,2) NOT NULL COMMENT '差异 = 实盘 - 账面' DEFAULT '0.00', PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`payment\` (\`company_id\` int NOT NULL COMMENT '所属租户', \`id\` int NOT NULL AUTO_INCREMENT, \`doc_no\` varchar(32) NOT NULL, \`type\` varchar(16) NOT NULL COMMENT 'pay=付款给供应商 receive=客户收款', \`partner_type\` varchar(16) NOT NULL, \`partner_id\` int NOT NULL, \`partner_name\` varchar(64) NOT NULL, \`amount\` decimal(12,2) NOT NULL DEFAULT '0.00', \`order_no\` varchar(32) NULL COMMENT '关联订单号', \`pay_date\` date NOT NULL, \`method\` varchar(32) NULL COMMENT '支付方式', \`remark\` varchar(255) NULL, \`created_by\` int NULL, \`created_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), UNIQUE INDEX \`IDX_c1f68522e5c1c24114f38040cd\` (\`company_id\`, \`doc_no\`), PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`DROP INDEX \`IDX_c1f68522e5c1c24114f38040cd\` ON \`payment\``);
        await queryRunner.query(`DROP TABLE \`payment\``);
        await queryRunner.query(`DROP TABLE \`stocktake_item\``);
        await queryRunner.query(`DROP INDEX \`IDX_18f72a9ee0258a1a4435b8d955\` ON \`stocktake\``);
        await queryRunner.query(`DROP TABLE \`stocktake\``);
        await queryRunner.query(`DROP TABLE \`inventory_record\``);
        await queryRunner.query(`DROP INDEX \`IDX_2aa58340b21f8eb450603b09e4\` ON \`inventory\``);
        await queryRunner.query(`DROP TABLE \`inventory\``);
        await queryRunner.query(`DROP TABLE \`sale_outbound_item\``);
        await queryRunner.query(`DROP INDEX \`IDX_38ce723a63c1fabf190af97fe9\` ON \`sale_outbound\``);
        await queryRunner.query(`DROP TABLE \`sale_outbound\``);
        await queryRunner.query(`DROP TABLE \`purchase_inbound_item\``);
        await queryRunner.query(`DROP INDEX \`IDX_4c8d9f2da9306e8768eaeb01df\` ON \`purchase_inbound\``);
        await queryRunner.query(`DROP TABLE \`purchase_inbound\``);
        await queryRunner.query(`DROP TABLE \`sale_order_item\``);
        await queryRunner.query(`DROP INDEX \`IDX_92db8b47c37bb286279f5c5f08\` ON \`sale_order\``);
        await queryRunner.query(`DROP TABLE \`sale_order\``);
        await queryRunner.query(`DROP TABLE \`purchase_order_item\``);
        await queryRunner.query(`DROP INDEX \`IDX_b26e19e4aaf364e7d057284c5d\` ON \`purchase_order\``);
        await queryRunner.query(`DROP TABLE \`purchase_order\``);
        await queryRunner.query(`DROP INDEX \`IDX_da15043b367546a1b25470accd\` ON \`customer\``);
        await queryRunner.query(`DROP TABLE \`customer\``);
        await queryRunner.query(`DROP INDEX \`IDX_7098388282f53f8c138e5fb60d\` ON \`supplier\``);
        await queryRunner.query(`DROP TABLE \`supplier\``);
        await queryRunner.query(`DROP INDEX \`IDX_d4a93f0caa54cce1e3e76bd987\` ON \`product\``);
        await queryRunner.query(`DROP TABLE \`product\``);
        await queryRunner.query(`DROP TABLE \`product_category\``);
        await queryRunner.query(`DROP TABLE \`sys_operation_log\``);
        await queryRunner.query(`DROP INDEX \`IDX_ba9809c4237d793d905045f04e\` ON \`sys_permission\``);
        await queryRunner.query(`DROP TABLE \`sys_permission\``);
        await queryRunner.query(`DROP INDEX \`IDX_2e8de9f75bef43b05dc1eb09ed\` ON \`sys_user_role\``);
        await queryRunner.query(`DROP TABLE \`sys_user_role\``);
        await queryRunner.query(`DROP INDEX \`IDX_980f2d8e546d791d992408b2c4\` ON \`sys_role_permission\``);
        await queryRunner.query(`DROP TABLE \`sys_role_permission\``);
        await queryRunner.query(`DROP INDEX \`IDX_03ed73db3445ce410474d1cc7f\` ON \`sys_role\``);
        await queryRunner.query(`DROP TABLE \`sys_role\``);
        await queryRunner.query(`DROP INDEX \`IDX_73b9691048355487ae9dd14aa6\` ON \`sys_user\``);
        await queryRunner.query(`DROP TABLE \`sys_user\``);
        await queryRunner.query(`DROP INDEX \`IDX_b1bb8505abe259d04b317bd799\` ON \`tenant\``);
        await queryRunner.query(`DROP TABLE \`tenant\``);
    }

}
